### PR TITLE
Gene macro, partial_eq and a few unit tests

### PR DESCRIPTION
**Pull request by BradenEverson**
Hey! 

I've been interested in genomics lately and wanted to contribute a bit to the open source Rust community while doing it. In this PR I haven't done anything out of this world, just created a macro to create new genes by calling:
```Rust
let gene: Gene = gene!(n);
```
Where `n` is the number of markers. I also changed the `is_equal` method to take references to the two genes to make it less consuming, and used that as a backend to implement partial_eq so we can use `==` and `!=` directly with genes. If you'd be interested, I'd love to work with you moving forward on this crate and possibly incorporate protein synthesis into it as well. 

Cheers!

Braden

### CODE REVIEW

**Comment by r1cebank** [comment]
Thanks for the contribution, let me know if you wanna incorporate other features in 👍

**Comment by BradenEverson** [comment]
> Thanks for the contribution, let me know if you wanna incorporate other features in 👍

Of course! I've been learning rust lately and absolutely loving it! Do you have any features you had in mind that you'd like implemented? I'd love to try some of them out

**Comment by r1cebank** [comment]
@BradenEverson sounds good, I am loving rust as well, it's been a while since I wrote any rust code tho 🤣 I don't have anything particular in mind, you mentioned protein synthesis in the PR, I wonder if you want to add something like that. I will add some autobuild and publish in the workflow later.

**Comment by BradenEverson** [comment]
@r1cebank That sounds good! I'll look into doing some protein synth in that case, and possibly work on implementing genome file parsing too.

**Comment by r1cebank** [comment]
@BradenEverson Awesome, let me know if you need me to help on anything, would love to know more about protein synth.

**Pull request merged**
